### ISSUE TITLE
Cannot find module ol-integration

### ISSUE THREAD

**Issue by JulioJu** [OSHistory/ng7-ol5-demo#2]
Hi,

Thanks for your project

But when I run `yarn install && ng serve` I have error 

```
ERROR in src/app/app.component.ts(3,30): error TS2307: Cannot find module 'ol-integration'.
src/app/app.module.ts(4,37): error TS2307: Cannot find module 'ol-integration'.
```

Could you help me please ?

Thanks in advance !

**Comment by OSHistory** [comment]
Hi there, 

You need to actually buid the library first:

`npm run build` which actually runs `ng build ol-integration`

I added the library integration later on, but missed to include it 
in the Readme, so thanks for the hint

**Comment by OSHistory** [comment]
I updated the Readme accordingly

**Comment by JulioJu** [comment]
@OSHistory 

Thanks for your answer. 

Actually `npm run build` run only `ng build`, and no `ng build ol-integration`.  To build `ol-integration` we must run `npm run build ol-integration`. Maybe we must update package.json, or the README. ?

**Comment by OSHistory** [comment]
@JulioJu  
Yes i mistyped in my comment (meant to type `ǹpm run build_lib`). 
The readme has it right, though. 
Thanks for pointing it out!
